#!/usr/bin/python3

import argparse
from contextlib import contextmanager
import os
import subprocess
import tempfile
import shutil


@contextmanager
def in_tempdir():
    cwd = os.getcwd()
    tmpdir = tempfile.mkdtemp()
    os.chdir(tmpdir)
    yield tmpdir
    os.chdir(cwd)
    shutil.rmtree(tmpdir)


parser = argparse.ArgumentParser()
parser.add_argument('packages', nargs='+')
parser.add_argument('--arch', default='armhf')
parser.add_argument('--sysroot',
                    default='/opt/pi-tools/arm-bcm2708hardfp-linux-gnueabi/')

if __name__ == '__main__':
    args = parser.parse_args()

    for package in args.packages:
        name = package + ':' + args.arch
        print('Downloading {} using apt-get...'.format(name))

        with in_tempdir() as tmpdir:
            subprocess.check_call(['apt-get', 'download', name])

            files = os.listdir(tmpdir)

            assert len(files) == 1
            debfile = files[0]
            assert debfile.endswith('.deb')

            print('Extracting to {}'.format(args.sysroot))
            subprocess.check_call(['dpkg', '-x', debfile, args.sysroot])

    print('Successfully installed {}'.format(', '.join(args.packages)))
